# Use the official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install any necessary dependencies
RUN apt-get update && \
    apt-get install -y zip && \
    rm -rf /var/lib/apt/lists/*

COPY requirements/ .

RUN pip install -r lambda.txt -t /opt/python/

CMD cd /opt && zip -r9 /app/lambda-layer.zip .
